configured_endpoints: 424
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/wisconsin-property-managers%2Fwpm-mcp-server-4a60c99cfbcc8deeb8a84ab946c6b4c60d71b763d22b86ae0edf5965a77ec53d.yml
openapi_spec_hash: b698752bb0b5f0d5e33d482aba1cfd71
config_hash: 437277da1a5d623a623a9fae3c837389
