// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'wpm-mcp-server-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../';
import WpmMcpServer from 'wpm-mcp-server';

export const metadata: Metadata = {
  resource: 'vendors',
  operation: 'write',
  tags: [],
  httpMethod: 'put',
  httpPath: '/v1/vendors/{vendorId}',
  operationId: 'ExternalApiVendors_UpdateVendor',
};

export const tool: Tool = {
  name: 'update_vendors',
  description:
    'Updates a vendor.\r\n            \r\n\r\n<strong>NOTE:</strong> Any field not included in the update request will be set to either an empty string or `null` in the database depending on the field definition. \r\nThe recommended workflow to ensure no data is inadvertently overwritten is to execute a `GET` request for the resource you\'re about to update and then use this response to fill any of the fields that are not being updated.\r\n            \r\n\r\n<h4>Required permission(s):</h4><span class="permissionBlock">Maintenance > Vendors</span> - `View` `Edit`',
  inputSchema: {
    type: 'object',
    properties: {
      vendorId: {
        type: 'integer',
      },
      CategoryId: {
        type: 'integer',
        description: 'The unique identifier of the vendor category.',
      },
      IsCompany: {
        type: 'boolean',
        description: 'Indicates whether the vendor should be considered a company or person.',
      },
      AccountNumber: {
        type: 'string',
        description: 'The account number of the vendor. The value cannot exceed 30 characters.',
      },
      Address: {
        type: 'object',
        description: 'Address.',
        properties: {
          AddressLine1: {
            type: 'string',
            description:
              'Address line 1 (e.g., street, PO Box, or company name). This value cannot exceed 100 characters.',
          },
          Country: {
            type: 'string',
            description: 'Country. Must be a valid `Country` enumeration value.',
            enum: [
              'Afghanistan',
              'Akrotiri',
              'Albania',
              'Algeria',
              'AmericanSamoa',
              'Andorra',
              'Angola',
              'Anguilla',
              'Antarctica',
              'AntiguaandBarbuda',
              'Argentina',
              'Armenia',
              'Aruba',
              'AshmoreandCartierIslands',
              'Australia',
              'Austria',
              'Azerbaijan',
              'Bahamas',
              'Bahrain',
              'Bangladesh',
              'Barbados',
              'BassasdaIndia',
              'Belarus',
              'Belgium',
              'Belize',
              'Benin',
              'Bermuda',
              'Bhutan',
              'Bolivia',
              'BosniaandHerzegovina',
              'Botswana',
              'BouvetIsland',
              'Brazil',
              'BritishIndianOceanTerritory',
              'BritishVirginIslands',
              'Brunei',
              'Bulgaria',
              'BurkinaFaso',
              'Burma',
              'Burundi',
              'Cambodia',
              'Cameroon',
              'Canada',
              'CapeVerde',
              'CaymanIslands',
              'CentralAfricanRepublic',
              'Chad',
              'Chile',
              'China',
              'ChristmasIsland',
              'ClippertonIsland',
              'CocosIslands',
              'Colombia',
              'Comoros',
              'DemocraticRepublicOfTheCongo',
              'RepublicOfTheCongo',
              'CookIslands',
              'CoralSeaIslands',
              'CostaRica',
              'CotedIvoire',
              'Croatia',
              'Cuba',
              'Cyprus',
              'CzechRepublic',
              'Denmark',
              'Dhekelia',
              'Djibouti',
              'Dominica',
              'DominicanRepublic',
              'Ecuador',
              'Egypt',
              'ElSalvador',
              'EquatorialGuinea',
              'Eritrea',
              'Estonia',
              'Ethiopia',
              'EuropaIsland',
              'FalklandIslands',
              'FaroeIslands',
              'Fiji',
              'Finland',
              'France',
              'FrenchGuiana',
              'FrenchPolynesia',
              'FrenchSouthernandAntarcticLands',
              'Gabon',
              'Gambia',
              'GazaStrip',
              'Georgia',
              'Germany',
              'Ghana',
              'Gibraltar',
              'GloriosoIslands',
              'Greece',
              'Greenland',
              'Grenada',
              'Guadeloupe',
              'Guam',
              'Guatemala',
              'Guernsey',
              'Guinea',
              'GuineaBissau',
              'Guyana',
              'Haiti',
              'HeardIslandandMcDonaldIslands',
              'VaticanCity',
              'Honduras',
              'HongKong',
              'Hungary',
              'Iceland',
              'India',
              'Indonesia',
              'Iran',
              'Iraq',
              'Ireland',
              'IsleofMan',
              'Israel',
              'Italy',
              'Jamaica',
              'JanMayen',
              'Japan',
              'Jersey',
              'Jordan',
              'JuandeNovaIsland',
              'Kazakhstan',
              'Kenya',
              'Kiribati',
              'NorthKorea',
              'SouthKorea',
              'Kuwait',
              'Kyrgyzstan',
              'Laos',
              'Latvia',
              'Lebanon',
              'Lesotho',
              'Liberia',
              'Libya',
              'Liechtenstein',
              'Lithuania',
              'Luxembourg',
              'Macau',
              'Macedonia',
              'Madagascar',
              'Malawi',
              'Malaysia',
              'Maldives',
              'Mali',
              'Malta',
              'MarshallIslands',
              'Martinique',
              'Mauritania',
              'Mauritius',
              'Mayotte',
              'Mexico',
              'Micronesia',
              'Moldova',
              'Monaco',
              'Mongolia',
              'Montserrat',
              'Morocco',
              'Mozambique',
              'Namibia',
              'Nauru',
              'NavassaIsland',
              'Nepal',
              'Netherlands',
              'NetherlandsAntilles',
              'NewCaledonia',
              'NewZealand',
              'Nicaragua',
              'Niger',
              'Nigeria',
              'Niue',
              'NorfolkIsland',
              'NorthernMarianaIslands',
              'Norway',
              'Oman',
              'Pakistan',
              'Palau',
              'Panama',
              'PapuaNewGuinea',
              'ParacelIslands',
              'Paraguay',
              'Peru',
              'Philippines',
              'PitcairnIslands',
              'Poland',
              'Portugal',
              'PuertoRico',
              'Qatar',
              'Reunion',
              'Romania',
              'Russia',
              'Rwanda',
              'SaintHelena',
              'SaintKittsandNevis',
              'SaintLucia',
              'SaintPierreandMiquelon',
              'SaintVincentandtheGrenadines',
              'Samoa',
              'SanMarino',
              'SaoTomeandPrincipe',
              'SaudiArabia',
              'Senegal',
              'SerbiaandMontenegro',
              'Seychelles',
              'SierraLeone',
              'Singapore',
              'Slovakia',
              'Slovenia',
              'SolomonIslands',
              'Somalia',
              'SouthAfrica',
              'SouthGeorgiaandtheSouthSandwichIslands',
              'Spain',
              'SpratlyIslands',
              'SriLanka',
              'Sudan',
              'Suriname',
              'Svalbard',
              'Swaziland',
              'Sweden',
              'Switzerland',
              'Syria',
              'Taiwan',
              'Tajikistan',
              'Tanzania',
              'Thailand',
              'TimorLeste',
              'Togo',
              'Tokelau',
              'Tonga',
              'TrinidadandTobago',
              'TromelinIsland',
              'Tunisia',
              'Turkey',
              'Turkmenistan',
              'TurksandCaicosIslands',
              'Tuvalu',
              'Uganda',
              'Ukraine',
              'UnitedArabEmirates',
              'UnitedKingdom',
              'UnitedStates',
              'Uruguay',
              'Uzbekistan',
              'Vanuatu',
              'Venezuela',
              'Vietnam',
              'VirginIslands',
              'WakeIsland',
              'WallisandFutuna',
              'WestBank',
              'WesternSahara',
              'Yemen',
              'Zambia',
              'Zimbabwe',
            ],
          },
          PostalCode: {
            type: 'string',
            description: 'ZIP or postal code.',
          },
          AddressLine2: {
            type: 'string',
            description:
              'Address line 2 (e.g., apartment, suite, unit, or building). This value cannot exceed 100 characters.',
          },
          AddressLine3: {
            type: 'string',
            description: 'Address line 3.  This value cannot exceed 100 characters.',
          },
          City: {
            type: 'string',
            description: 'City, district, suburb, town, or village. This value cannot exceed 100 characters.',
          },
          State: {
            type: 'string',
            description:
              'State, county, province, or region. When `Country` is set to `UnitedStates` this value must be a valid state name or abbreviation. If the value is `Canada` this value must be a valid Canadian province. For all other countries this field is optional and not validated.',
          },
        },
        required: ['AddressLine1', 'Country', 'PostalCode'],
      },
      AlternateEmail: {
        type: 'string',
        description: 'Alternate email for the vendor.',
      },
      Comments: {
        type: 'string',
        description: 'Comments about the vendor. The value cannot exceed 65,535 characters.',
      },
      CompanyName: {
        type: 'string',
        description:
          'Company name of the vendor. Required if `IsCompany` is `true`. The value cannot exceed 127 characters.',
      },
      ExpenseGlAccountId: {
        type: 'integer',
        description:
          'The unique identifier of the default expense general ledger account to associate with the vendor.',
      },
      FirstName: {
        type: 'string',
        description:
          'First name of the vendor. Required if `IsCompany` is `false`. The value cannot exceed 127 characters.',
      },
      LastName: {
        type: 'string',
        description:
          'Last name of the vendor. Required if `IsCompany` is `false`. The value cannot exceed 127 characters.',
      },
      PhoneNumbers: {
        type: 'object',
        description: 'Phone numbers.',
        properties: {
          Fax: {
            type: 'string',
            description:
              'Fax number. If provided, must be between 10 and 20 characters, ideally formatted as `(123) 123-1234`.',
          },
          Home: {
            type: 'string',
            description:
              'Home phone number. If provided, must be between 10 and 20 characters, ideally formatted as `(123) 123-1234`.',
          },
          Mobile: {
            type: 'string',
            description:
              'Mobile phone number. If provided, must be between 10 and 20 characters, ideally formatted as `(123) 123-1234`.',
          },
          Work: {
            type: 'string',
            description:
              'Work phone number. If provided, must be between 10 and 20 characters, ideally formatted as `(123) 123-1234`.',
          },
        },
        required: [],
      },
      PrimaryEmail: {
        type: 'string',
        description: 'Primary email for the vendor.',
      },
      TaxInformation: {
        type: 'object',
        description: 'Tax information.',
        properties: {
          IncludeIn1099: {
            type: 'boolean',
            description: 'Indicates whether the vendor should be included in 1099 form generation.',
          },
          Address: {
            type: 'object',
            description: 'Address.',
            properties: {
              AddressLine1: {
                type: 'string',
                description:
                  'Address line 1 (e.g., street, PO Box, or company name). This value cannot exceed 100 characters.',
              },
              Country: {
                type: 'string',
                description: 'Country. Must be a valid `Country` enumeration value.',
                enum: [
                  'Afghanistan',
                  'Akrotiri',
                  'Albania',
                  'Algeria',
                  'AmericanSamoa',
                  'Andorra',
                  'Angola',
                  'Anguilla',
                  'Antarctica',
                  'AntiguaandBarbuda',
                  'Argentina',
                  'Armenia',
                  'Aruba',
                  'AshmoreandCartierIslands',
                  'Australia',
                  'Austria',
                  'Azerbaijan',
                  'Bahamas',
                  'Bahrain',
                  'Bangladesh',
                  'Barbados',
                  'BassasdaIndia',
                  'Belarus',
                  'Belgium',
                  'Belize',
                  'Benin',
                  'Bermuda',
                  'Bhutan',
                  'Bolivia',
                  'BosniaandHerzegovina',
                  'Botswana',
                  'BouvetIsland',
                  'Brazil',
                  'BritishIndianOceanTerritory',
                  'BritishVirginIslands',
                  'Brunei',
                  'Bulgaria',
                  'BurkinaFaso',
                  'Burma',
                  'Burundi',
                  'Cambodia',
                  'Cameroon',
                  'Canada',
                  'CapeVerde',
                  'CaymanIslands',
                  'CentralAfricanRepublic',
                  'Chad',
                  'Chile',
                  'China',
                  'ChristmasIsland',
                  'ClippertonIsland',
                  'CocosIslands',
                  'Colombia',
                  'Comoros',
                  'DemocraticRepublicOfTheCongo',
                  'RepublicOfTheCongo',
                  'CookIslands',
                  'CoralSeaIslands',
                  'CostaRica',
                  'CotedIvoire',
                  'Croatia',
                  'Cuba',
                  'Cyprus',
                  'CzechRepublic',
                  'Denmark',
                  'Dhekelia',
                  'Djibouti',
                  'Dominica',
                  'DominicanRepublic',
                  'Ecuador',
                  'Egypt',
                  'ElSalvador',
                  'EquatorialGuinea',
                  'Eritrea',
                  'Estonia',
                  'Ethiopia',
                  'EuropaIsland',
                  'FalklandIslands',
                  'FaroeIslands',
                  'Fiji',
                  'Finland',
                  'France',
                  'FrenchGuiana',
                  'FrenchPolynesia',
                  'FrenchSouthernandAntarcticLands',
                  'Gabon',
                  'Gambia',
                  'GazaStrip',
                  'Georgia',
                  'Germany',
                  'Ghana',
                  'Gibraltar',
                  'GloriosoIslands',
                  'Greece',
                  'Greenland',
                  'Grenada',
                  'Guadeloupe',
                  'Guam',
                  'Guatemala',
                  'Guernsey',
                  'Guinea',
                  'GuineaBissau',
                  'Guyana',
                  'Haiti',
                  'HeardIslandandMcDonaldIslands',
                  'VaticanCity',
                  'Honduras',
                  'HongKong',
                  'Hungary',
                  'Iceland',
                  'India',
                  'Indonesia',
                  'Iran',
                  'Iraq',
                  'Ireland',
                  'IsleofMan',
                  'Israel',
                  'Italy',
                  'Jamaica',
                  'JanMayen',
                  'Japan',
                  'Jersey',
                  'Jordan',
                  'JuandeNovaIsland',
                  'Kazakhstan',
                  'Kenya',
                  'Kiribati',
                  'NorthKorea',
                  'SouthKorea',
                  'Kuwait',
                  'Kyrgyzstan',
                  'Laos',
                  'Latvia',
                  'Lebanon',
                  'Lesotho',
                  'Liberia',
                  'Libya',
                  'Liechtenstein',
                  'Lithuania',
                  'Luxembourg',
                  'Macau',
                  'Macedonia',
                  'Madagascar',
                  'Malawi',
                  'Malaysia',
                  'Maldives',
                  'Mali',
                  'Malta',
                  'MarshallIslands',
                  'Martinique',
                  'Mauritania',
                  'Mauritius',
                  'Mayotte',
                  'Mexico',
                  'Micronesia',
                  'Moldova',
                  'Monaco',
                  'Mongolia',
                  'Montserrat',
                  'Morocco',
                  'Mozambique',
                  'Namibia',
                  'Nauru',
                  'NavassaIsland',
                  'Nepal',
                  'Netherlands',
                  'NetherlandsAntilles',
                  'NewCaledonia',
                  'NewZealand',
                  'Nicaragua',
                  'Niger',
                  'Nigeria',
                  'Niue',
                  'NorfolkIsland',
                  'NorthernMarianaIslands',
                  'Norway',
                  'Oman',
                  'Pakistan',
                  'Palau',
                  'Panama',
                  'PapuaNewGuinea',
                  'ParacelIslands',
                  'Paraguay',
                  'Peru',
                  'Philippines',
                  'PitcairnIslands',
                  'Poland',
                  'Portugal',
                  'PuertoRico',
                  'Qatar',
                  'Reunion',
                  'Romania',
                  'Russia',
                  'Rwanda',
                  'SaintHelena',
                  'SaintKittsandNevis',
                  'SaintLucia',
                  'SaintPierreandMiquelon',
                  'SaintVincentandtheGrenadines',
                  'Samoa',
                  'SanMarino',
                  'SaoTomeandPrincipe',
                  'SaudiArabia',
                  'Senegal',
                  'SerbiaandMontenegro',
                  'Seychelles',
                  'SierraLeone',
                  'Singapore',
                  'Slovakia',
                  'Slovenia',
                  'SolomonIslands',
                  'Somalia',
                  'SouthAfrica',
                  'SouthGeorgiaandtheSouthSandwichIslands',
                  'Spain',
                  'SpratlyIslands',
                  'SriLanka',
                  'Sudan',
                  'Suriname',
                  'Svalbard',
                  'Swaziland',
                  'Sweden',
                  'Switzerland',
                  'Syria',
                  'Taiwan',
                  'Tajikistan',
                  'Tanzania',
                  'Thailand',
                  'TimorLeste',
                  'Togo',
                  'Tokelau',
                  'Tonga',
                  'TrinidadandTobago',
                  'TromelinIsland',
                  'Tunisia',
                  'Turkey',
                  'Turkmenistan',
                  'TurksandCaicosIslands',
                  'Tuvalu',
                  'Uganda',
                  'Ukraine',
                  'UnitedArabEmirates',
                  'UnitedKingdom',
                  'UnitedStates',
                  'Uruguay',
                  'Uzbekistan',
                  'Vanuatu',
                  'Venezuela',
                  'Vietnam',
                  'VirginIslands',
                  'WakeIsland',
                  'WallisandFutuna',
                  'WestBank',
                  'WesternSahara',
                  'Yemen',
                  'Zambia',
                  'Zimbabwe',
                ],
              },
              PostalCode: {
                type: 'string',
                description: 'ZIP or postal code.',
              },
              AddressLine2: {
                type: 'string',
                description:
                  'Address line 2 (e.g., apartment, suite, unit, or building). This value cannot exceed 100 characters.',
              },
              AddressLine3: {
                type: 'string',
                description: 'Address line 3.  This value cannot exceed 100 characters.',
              },
              City: {
                type: 'string',
                description:
                  'City, district, suburb, town, or village. This value cannot exceed 100 characters.',
              },
              State: {
                type: 'string',
                description:
                  'State, county, province, or region. When `Country` is set to `UnitedStates` this value must be a valid state name or abbreviation. If the value is `Canada` this value must be a valid Canadian province. For all other countries this field is optional and not validated.',
              },
            },
            required: ['AddressLine1', 'Country', 'PostalCode'],
          },
          TaxPayerId: {
            type: 'string',
            description:
              'The unique identifier of the tax payer. Required if `TaxPayerType` is set. Format the values based on the `TaxPayerIdType` that is specified in the request. `SSN` must be formatted as 123-45-6789. `EIN` must be formatted as 12-3456789.',
          },
          TaxPayerName1: {
            type: 'string',
            description: 'The tax payer name 1. The value cannot exceed 40 characters.',
          },
          TaxPayerName2: {
            type: 'string',
            description: 'The tax payer name 2. The value cannot exceed 40 characters.',
          },
          TaxPayerType: {
            type: 'string',
            description: 'The tax payer type. Required if `TaxPayerId` is set.',
            enum: ['SSN', 'EIN'],
          },
        },
        required: ['IncludeIn1099'],
      },
      VendorInsurance: {
        $ref: '#/$defs/vendor_insurance_save',
      },
      Website: {
        type: 'string',
        description:
          'The website of the vendor. The value must be a valid URL. For example "http://www.example.com". The value cannot exceed 100 characters.',
      },
    },
    $defs: {
      vendor_insurance_save: {
        type: 'object',
        description: 'Vendor insurance information.',
        properties: {
          ExpirationDate: {
            type: 'string',
            description: 'Expiration date of the insurance policy. The date must be formatted as YYYY-MM-DD.',
            format: 'date',
          },
          PolicyNumber: {
            type: 'string',
            description: 'Insurance policy number. This value can not exceed 65 characters.',
          },
          Provider: {
            type: 'string',
            description: 'Insurance provider. This value can not exceed 65 characters.',
          },
        },
        required: [],
      },
    },
  },
};

export const handler = async (client: WpmMcpServer, args: Record<string, unknown> | undefined) => {
  const { vendorId, ...body } = args as any;
  return asTextContentResult(await client.vendors.update(vendorId, body));
};

export default { metadata, tool, handler };
