// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, Endpoint, HandlerFunction } from './types';

export { Metadata, Endpoint, HandlerFunction };

import create_auto_allocated_payment_applications from './applications/create-auto-allocated-payment-applications';
import create_payment_reversal_applications from './applications/create-payment-reversal-applications';
import list_outstanding_balances_applications from './applications/list-outstanding-balances-applications';
import retrieve_applications_transactions from './applications/transactions/retrieve-applications-transactions';
import list_applications_transactions from './applications/transactions/list-applications-transactions';
import create_applications_charges from './applications/charges/create-applications-charges';
import retrieve_applications_charges from './applications/charges/retrieve-applications-charges';
import update_applications_charges from './applications/charges/update-applications-charges';
import list_applications_charges from './applications/charges/list-applications-charges';
import create_applications_payments from './applications/payments/create-applications-payments';
import update_applications_payments from './applications/payments/update-applications-payments';
import create_applications_refunds from './applications/refunds/create-applications-refunds';
import retrieve_applications_refunds from './applications/refunds/retrieve-applications-refunds';
import create_associations from './associations/create-associations';
import retrieve_associations from './associations/retrieve-associations';
import update_associations from './associations/update-associations';
import list_associations from './associations/list-associations';
import inactivate_associations from './associations/inactivate-associations';
import list_bank_lockbox_data_associations from './associations/list-bank-lockbox-data-associations';
import reactivate_associations from './associations/reactivate-associations';
import create_associations_ownershipaccounts from './associations/ownershipaccounts/create-associations-ownershipaccounts';
import retrieve_associations_ownershipaccounts from './associations/ownershipaccounts/retrieve-associations-ownershipaccounts';
import update_associations_ownershipaccounts from './associations/ownershipaccounts/update-associations-ownershipaccounts';
import list_associations_ownershipaccounts from './associations/ownershipaccounts/list-associations-ownershipaccounts';
import autoallocatedpayments_associations_ownershipaccounts from './associations/ownershipaccounts/autoallocatedpayments-associations-ownershipaccounts';
import credits_associations_ownershipaccounts from './associations/ownershipaccounts/credits-associations-ownershipaccounts';
import retrieve_outstandingbalances_associations_ownershipaccounts from './associations/ownershipaccounts/retrieve-outstandingbalances-associations-ownershipaccounts';
import retrieve_ownershipaccounts_associations_transactions from './associations/ownershipaccounts/transactions/retrieve-ownershipaccounts-associations-transactions';
import list_ownershipaccounts_associations_transactions from './associations/ownershipaccounts/transactions/list-ownershipaccounts-associations-transactions';
import create_ownershipaccounts_associations_architecturalrequests from './associations/ownershipaccounts/architecturalrequests/create-ownershipaccounts-associations-architecturalrequests';
import retrieve_ownershipaccounts_associations_architecturalrequests from './associations/ownershipaccounts/architecturalrequests/retrieve-ownershipaccounts-associations-architecturalrequests';
import list_ownershipaccounts_associations_architecturalrequests from './associations/ownershipaccounts/architecturalrequests/list-ownershipaccounts-associations-architecturalrequests';
import retrieve_architecturalrequests_ownershipaccounts_associations_files from './associations/ownershipaccounts/architecturalrequests/files/retrieve-architecturalrequests-ownershipaccounts-associations-files';
import list_architecturalrequests_ownershipaccounts_associations_files from './associations/ownershipaccounts/architecturalrequests/files/list-architecturalrequests-ownershipaccounts-associations-files';
import downloadrequests_architecturalrequests_ownershipaccounts_associations_files from './associations/ownershipaccounts/architecturalrequests/files/downloadrequests-architecturalrequests-ownershipaccounts-associations-files';
import uploadrequests_architecturalrequests_ownershipaccounts_associations_files from './associations/ownershipaccounts/architecturalrequests/files/uploadrequests-architecturalrequests-ownershipaccounts-associations-files';
import create_ownershipaccounts_associations_charges from './associations/ownershipaccounts/charges/create-ownershipaccounts-associations-charges';
import retrieve_ownershipaccounts_associations_charges from './associations/ownershipaccounts/charges/retrieve-ownershipaccounts-associations-charges';
import update_ownershipaccounts_associations_charges from './associations/ownershipaccounts/charges/update-ownershipaccounts-associations-charges';
import list_ownershipaccounts_associations_charges from './associations/ownershipaccounts/charges/list-ownershipaccounts-associations-charges';
import create_ownershipaccounts_associations_payments from './associations/ownershipaccounts/payments/create-ownershipaccounts-associations-payments';
import update_ownershipaccounts_associations_payments from './associations/ownershipaccounts/payments/update-ownershipaccounts-associations-payments';
import create_ownershipaccounts_associations_refunds from './associations/ownershipaccounts/refunds/create-ownershipaccounts-associations-refunds';
import retrieve_ownershipaccounts_associations_refunds from './associations/ownershipaccounts/refunds/retrieve-ownershipaccounts-associations-refunds';
import create_ownershipaccounts_associations_applieddeposits from './associations/ownershipaccounts/applieddeposits/create-ownershipaccounts-associations-applieddeposits';
import update_ownershipaccounts_associations_applieddeposits from './associations/ownershipaccounts/applieddeposits/update-ownershipaccounts-associations-applieddeposits';
import list_ownershipaccounts_associations_recurringtransactions from './associations/ownershipaccounts/recurringtransactions/list-ownershipaccounts-associations-recurringtransactions';
import create_ownershipaccounts_associations_notes from './associations/ownershipaccounts/notes/create-ownershipaccounts-associations-notes';
import retrieve_ownershipaccounts_associations_notes from './associations/ownershipaccounts/notes/retrieve-ownershipaccounts-associations-notes';
import update_ownershipaccounts_associations_notes from './associations/ownershipaccounts/notes/update-ownershipaccounts-associations-notes';
import list_ownershipaccounts_associations_notes from './associations/ownershipaccounts/notes/list-ownershipaccounts-associations-notes';
import list_ownershipaccounts_associations_partialpaymentsettings from './associations/ownershipaccounts/partialpaymentsettings/list-ownershipaccounts-associations-partialpaymentsettings';
import patch_all_ownershipaccounts_associations_partialpaymentsettings from './associations/ownershipaccounts/partialpaymentsettings/patch-all-ownershipaccounts-associations-partialpaymentsettings';
import create_ownershipaccounts_associations_recurringcharges from './associations/ownershipaccounts/recurringcharges/create-ownershipaccounts-associations-recurringcharges';
import retrieve_ownershipaccounts_associations_recurringcharges from './associations/ownershipaccounts/recurringcharges/retrieve-ownershipaccounts-associations-recurringcharges';
import create_ownershipaccounts_associations_recurringcredits from './associations/ownershipaccounts/recurringcredits/create-ownershipaccounts-associations-recurringcredits';
import retrieve_ownershipaccounts_associations_recurringcredits from './associations/ownershipaccounts/recurringcredits/retrieve-ownershipaccounts-associations-recurringcredits';
import create_ownershipaccounts_associations_recurringpayments from './associations/ownershipaccounts/recurringpayments/create-ownershipaccounts-associations-recurringpayments';
import retrieve_ownershipaccounts_associations_recurringpayments from './associations/ownershipaccounts/recurringpayments/retrieve-ownershipaccounts-associations-recurringpayments';
import create_associations_units from './associations/units/create-associations-units';
import retrieve_associations_units from './associations/units/retrieve-associations-units';
import update_associations_units from './associations/units/update-associations-units';
import list_associations_units from './associations/units/list-associations-units';
import create_units_associations_notes from './associations/units/notes/create-units-associations-notes';
import retrieve_units_associations_notes from './associations/units/notes/retrieve-units-associations-notes';
import update_units_associations_notes from './associations/units/notes/update-units-associations-notes';
import list_units_associations_notes from './associations/units/notes/list-units-associations-notes';
import create_associations_owners from './associations/owners/create-associations-owners';
import retrieve_associations_owners from './associations/owners/retrieve-associations-owners';
import update_associations_owners from './associations/owners/update-associations-owners';
import list_associations_owners from './associations/owners/list-associations-owners';
import create_owners_associations_notes from './associations/owners/notes/create-owners-associations-notes';
import retrieve_owners_associations_notes from './associations/owners/notes/retrieve-owners-associations-notes';
import update_owners_associations_notes from './associations/owners/notes/update-owners-associations-notes';
import list_owners_associations_notes from './associations/owners/notes/list-owners-associations-notes';
import retrieve_owners_associations_units from './associations/owners/units/retrieve-owners-associations-units';
import update_owners_associations_units from './associations/owners/units/update-owners-associations-units';
import list_owners_associations_units from './associations/owners/units/list-owners-associations-units';
import create_associations_tenants from './associations/tenants/create-associations-tenants';
import retrieve_associations_tenants from './associations/tenants/retrieve-associations-tenants';
import update_associations_tenants from './associations/tenants/update-associations-tenants';
import list_associations_tenants from './associations/tenants/list-associations-tenants';
import create_tenants_associations_notes from './associations/tenants/notes/create-tenants-associations-notes';
import retrieve_tenants_associations_notes from './associations/tenants/notes/retrieve-tenants-associations-notes';
import update_tenants_associations_notes from './associations/tenants/notes/update-tenants-associations-notes';
import list_tenants_associations_notes from './associations/tenants/notes/list-tenants-associations-notes';
import create_associations_boardmembers from './associations/boardmembers/create-associations-boardmembers';
import retrieve_associations_boardmembers from './associations/boardmembers/retrieve-associations-boardmembers';
import update_associations_boardmembers from './associations/boardmembers/update-associations-boardmembers';
import list_associations_boardmembers from './associations/boardmembers/list-associations-boardmembers';
import delete_associations_boardmembers from './associations/boardmembers/delete-associations-boardmembers';
import retrieve_associations_epaysettings from './associations/epaysettings/retrieve-associations-epaysettings';
import update_associations_epaysettings from './associations/epaysettings/update-associations-epaysettings';
import list_associations_meterreadings from './associations/meterreadings/list-associations-meterreadings';
import update_meterreadings_associations_summary from './associations/meterreadings/summary/update-meterreadings-associations-summary';
import list_meterreadings_associations_summary from './associations/meterreadings/summary/list-meterreadings-associations-summary';
import delete_meterreadings_associations_summary from './associations/meterreadings/summary/delete-meterreadings-associations-summary';
import create_associations_notes from './associations/notes/create-associations-notes';
import retrieve_associations_notes from './associations/notes/retrieve-associations-notes';
import update_associations_notes from './associations/notes/update-associations-notes';
import list_associations_notes from './associations/notes/list-associations-notes';
import update_associations_vendors from './associations/vendors/update-associations-vendors';
import list_associations_vendors from './associations/vendors/list-associations-vendors';
import create_associations_appliances from './associations/appliances/create-associations-appliances';
import retrieve_associations_appliances from './associations/appliances/retrieve-associations-appliances';
import update_associations_appliances from './associations/appliances/update-associations-appliances';
import list_associations_appliances from './associations/appliances/list-associations-appliances';
import delete_associations_appliances from './associations/appliances/delete-associations-appliances';
import create_appliances_associations_servicehistory from './associations/appliances/servicehistory/create-appliances-associations-servicehistory';
import retrieve_appliances_associations_servicehistory from './associations/appliances/servicehistory/retrieve-appliances-associations-servicehistory';
import list_appliances_associations_servicehistory from './associations/appliances/servicehistory/list-appliances-associations-servicehistory';
import retrieve_files from './files/retrieve-files';
import update_files from './files/update-files';
import list_files from './files/list-files';
import create_upload_request_files from './files/create-upload-request-files';
import request_download_files from './files/request-download-files';
import retrieve_files_sharing from './files/sharing/retrieve-files-sharing';
import update_files_sharing from './files/sharing/update-files-sharing';
import create_files_categories from './files/categories/create-files-categories';
import retrieve_files_categories from './files/categories/retrieve-files-categories';
import update_files_categories from './files/categories/update-files-categories';
import list_files_categories from './files/categories/list-files-categories';
import create_leases from './leases/create-leases';
import retrieve_leases from './leases/retrieve-leases';
import update_leases from './leases/update-leases';
import list_leases from './leases/list-leases';
import create_autoallocated_payment_leases from './leases/create-autoallocated-payment-leases';
import create_credit_leases from './leases/create-credit-leases';
import create_payment_reversal_leases from './leases/create-payment-reversal-leases';
import list_outstanding_balances_leases from './leases/list-outstanding-balances-leases';
import list_renewal_history_leases from './leases/list-renewal-history-leases';
import retrieve_leases_transactions from './leases/transactions/retrieve-leases-transactions';
import list_leases_transactions from './leases/transactions/list-leases-transactions';
import create_leases_charges from './leases/charges/create-leases-charges';
import retrieve_leases_charges from './leases/charges/retrieve-leases-charges';
import update_leases_charges from './leases/charges/update-leases-charges';
import list_leases_charges from './leases/charges/list-leases-charges';
import create_leases_moveouts from './leases/moveouts/create-leases-moveouts';
import retrieve_leases_moveouts from './leases/moveouts/retrieve-leases-moveouts';
import list_leases_moveouts from './leases/moveouts/list-leases-moveouts';
import delete_leases_moveouts from './leases/moveouts/delete-leases-moveouts';
import create_leases_payments from './leases/payments/create-leases-payments';
import update_leases_payments from './leases/payments/update-leases-payments';
import create_leases_notes from './leases/notes/create-leases-notes';
import retrieve_leases_notes from './leases/notes/retrieve-leases-notes';
import update_leases_notes from './leases/notes/update-leases-notes';
import list_leases_notes from './leases/notes/list-leases-notes';
import create_leases_refunds from './leases/refunds/create-leases-refunds';
import retrieve_leases_refunds from './leases/refunds/retrieve-leases-refunds';
import create_leases_renewals from './leases/renewals/create-leases-renewals';
import retrieve_leases_renewals from './leases/renewals/retrieve-leases-renewals';
import list_leases_renewals from './leases/renewals/list-leases-renewals';
import list_upcoming_leases_renewals from './leases/renewals/list-upcoming-leases-renewals';
import create_leases_applieddeposits from './leases/applieddeposits/create-leases-applieddeposits';
import update_leases_applieddeposits from './leases/applieddeposits/update-leases-applieddeposits';
import list_leases_recurringtransactions from './leases/recurringtransactions/list-leases-recurringtransactions';
import list_all_leases_recurringtransactions from './leases/recurringtransactions/list-all-leases-recurringtransactions';
import retrieve_leases_epaysettings from './leases/epaysettings/retrieve-leases-epaysettings';
import update_leases_epaysettings from './leases/epaysettings/update-leases-epaysettings';
import retrieve_leases_partialpaymentsettings from './leases/partialpaymentsettings/retrieve-leases-partialpaymentsettings';
import update_leases_partialpaymentsettings from './leases/partialpaymentsettings/update-leases-partialpaymentsettings';
import create_leases_recurringcharges from './leases/recurringcharges/create-leases-recurringcharges';
import retrieve_leases_recurringcharges from './leases/recurringcharges/retrieve-leases-recurringcharges';
import create_leases_recurringcredits from './leases/recurringcredits/create-leases-recurringcredits';
import retrieve_leases_recurringcredits from './leases/recurringcredits/retrieve-leases-recurringcredits';
import create_leases_recurringpayments from './leases/recurringpayments/create-leases-recurringpayments';
import retrieve_leases_recurringpayments from './leases/recurringpayments/retrieve-leases-recurringpayments';
import create_leases_rent from './leases/rent/create-leases-rent';
import retrieve_leases_rent from './leases/rent/retrieve-leases-rent';
import update_leases_rent from './leases/rent/update-leases-rent';
import retrieve_all_leases_rent from './leases/rent/retrieve-all-leases-rent';
import retrieve_leases_rentersinsurance from './leases/rentersinsurance/retrieve-leases-rentersinsurance';
import retrieve_all_leases_rentersinsurance from './leases/rentersinsurance/retrieve-all-leases-rentersinsurance';
import create_leases_tenants from './leases/tenants/create-leases-tenants';
import retrieve_leases_tenants from './leases/tenants/retrieve-leases-tenants';
import update_leases_tenants from './leases/tenants/update-leases-tenants';
import retrieve_all_leases_tenants from './leases/tenants/retrieve-all-leases-tenants';
import create_tenants_leases_notes from './leases/tenants/notes/create-tenants-leases-notes';
import retrieve_tenants_leases_notes from './leases/tenants/notes/retrieve-tenants-leases-notes';
import update_tenants_leases_notes from './leases/tenants/notes/update-tenants-leases-notes';
import retrieve_all_tenants_leases_notes from './leases/tenants/notes/retrieve-all-tenants-leases-notes';
import create_rentals from './rentals/create-rentals';
import retrieve_rentals from './rentals/retrieve-rentals';
import update_rentals from './rentals/update-rentals';
import list_rentals from './rentals/list-rentals';
import inactivate_rentals from './rentals/inactivate-rentals';
import reactivate_rentals from './rentals/reactivate-rentals';
import create_rentals_units from './rentals/units/create-rentals-units';
import retrieve_rentals_units from './rentals/units/retrieve-rentals-units';
import update_rentals_units from './rentals/units/update-rentals-units';
import list_rentals_units from './rentals/units/list-rentals-units';
import retrieve_listings_rentals_units from './rentals/units/retrieve-listings-rentals-units';
import create_units_rentals_listing from './rentals/units/listing/create-units-rentals-listing';
import list_units_rentals_listing from './rentals/units/listing/list-units-rentals-listing';
import delete_all_units_rentals_listing from './rentals/units/listing/delete-all-units-rentals-listing';
import create_units_rentals_listingcontacts from './rentals/units/listingcontacts/create-units-rentals-listingcontacts';
import retrieve_units_rentals_listingcontacts from './rentals/units/listingcontacts/retrieve-units-rentals-listingcontacts';
import update_units_rentals_listingcontacts from './rentals/units/listingcontacts/update-units-rentals-listingcontacts';
import list_units_rentals_listingcontacts from './rentals/units/listingcontacts/list-units-rentals-listingcontacts';
import create_units_rentals_amenities from './rentals/units/amenities/create-units-rentals-amenities';
import list_units_rentals_amenities from './rentals/units/amenities/list-units-rentals-amenities';
import retrieve_units_rentals_images from './rentals/units/images/retrieve-units-rentals-images';
import update_units_rentals_images from './rentals/units/images/update-units-rentals-images';
import list_units_rentals_images from './rentals/units/images/list-units-rentals-images';
import delete_units_rentals_images from './rentals/units/images/delete-units-rentals-images';
import downloadrequests_units_rentals_images from './rentals/units/images/downloadrequests-units-rentals-images';
import update_order_units_rentals_images from './rentals/units/images/update-order-units-rentals-images';
import uploadrequests_units_rentals_images from './rentals/units/images/uploadrequests-units-rentals-images';
import videolinkrequests_units_rentals_images from './rentals/units/images/videolinkrequests-units-rentals-images';
import create_units_rentals_notes from './rentals/units/notes/create-units-rentals-notes';
import retrieve_units_rentals_notes from './rentals/units/notes/retrieve-units-rentals-notes';
import update_units_rentals_notes from './rentals/units/notes/update-units-rentals-notes';
import list_units_rentals_notes from './rentals/units/notes/list-units-rentals-notes';
import create_rentals_vendors from './rentals/vendors/create-rentals-vendors';
import list_rentals_vendors from './rentals/vendors/list-rentals-vendors';
import create_rentals_amenities from './rentals/amenities/create-rentals-amenities';
import list_rentals_amenities from './rentals/amenities/list-rentals-amenities';
import create_rentals_epaysettings from './rentals/epaysettings/create-rentals-epaysettings';
import list_rentals_epaysettings from './rentals/epaysettings/list-rentals-epaysettings';
import retrieve_rentals_images from './rentals/images/retrieve-rentals-images';
import update_rentals_images from './rentals/images/update-rentals-images';
import list_rentals_images from './rentals/images/list-rentals-images';
import delete_rentals_images from './rentals/images/delete-rentals-images';
import downloadrequests_rentals_images from './rentals/images/downloadrequests-rentals-images';
import update_order_rentals_images from './rentals/images/update-order-rentals-images';
import uploadrequests_rentals_images from './rentals/images/uploadrequests-rentals-images';
import videolinkrequests_rentals_images from './rentals/images/videolinkrequests-rentals-images';
import list_rentals_meterreadings from './rentals/meterreadings/list-rentals-meterreadings';
import create_meterreadings_rentals_summary from './rentals/meterreadings/summary/create-meterreadings-rentals-summary';
import list_meterreadings_rentals_summary from './rentals/meterreadings/summary/list-meterreadings-rentals-summary';
import delete_all_meterreadings_rentals_summary from './rentals/meterreadings/summary/delete-all-meterreadings-rentals-summary';
import create_rentals_notes from './rentals/notes/create-rentals-notes';
import retrieve_rentals_notes from './rentals/notes/retrieve-rentals-notes';
import update_rentals_notes from './rentals/notes/update-rentals-notes';
import list_rentals_notes from './rentals/notes/list-rentals-notes';
import create_rentals_appliances from './rentals/appliances/create-rentals-appliances';
import retrieve_rentals_appliances from './rentals/appliances/retrieve-rentals-appliances';
import update_rentals_appliances from './rentals/appliances/update-rentals-appliances';
import list_rentals_appliances from './rentals/appliances/list-rentals-appliances';
import delete_rentals_appliances from './rentals/appliances/delete-rentals-appliances';
import create_appliances_rentals_servicehistory from './rentals/appliances/servicehistory/create-appliances-rentals-servicehistory';
import retrieve_appliances_rentals_servicehistory from './rentals/appliances/servicehistory/retrieve-appliances-rentals-servicehistory';
import list_appliances_rentals_servicehistory from './rentals/appliances/servicehistory/list-appliances-rentals-servicehistory';
import create_rentals_owners from './rentals/owners/create-rentals-owners';
import retrieve_rentals_owners from './rentals/owners/retrieve-rentals-owners';
import update_rentals_owners from './rentals/owners/update-rentals-owners';
import list_rentals_owners from './rentals/owners/list-rentals-owners';
import create_owners_rentals_notes from './rentals/owners/notes/create-owners-rentals-notes';
import retrieve_owners_rentals_notes from './rentals/owners/notes/retrieve-owners-rentals-notes';
import update_owners_rentals_notes from './rentals/owners/notes/update-owners-rentals-notes';
import list_owners_rentals_notes from './rentals/owners/notes/list-owners-rentals-notes';
import retrieve_users from './users/retrieve-users';
import list_users from './users/list-users';
import retrieve_userroles from './userroles/retrieve-userroles';
import list_userroles from './userroles/list-userroles';
import retrieve_account_administration from './administration/retrieve-account-administration';
import retrieve_accounting_lock_periods_administration from './administration/retrieve-accounting-lock-periods-administration';
import retrieve_residentsettings_administration_partialpaymentsettings from './administration/residentsettings/partialpaymentsettings/retrieve-residentsettings-administration-partialpaymentsettings';
import update_residentsettings_administration_partialpaymentsettings from './administration/residentsettings/partialpaymentsettings/update-residentsettings-administration-partialpaymentsettings';
import create_applicants from './applicants/create-applicants';
import retrieve_applicants from './applicants/retrieve-applicants';
import update_applicants from './applicants/update-applicants';
import list_applicants from './applicants/list-applicants';
import retrieve_applicants_applications from './applicants/applications/retrieve-applicants-applications';
import update_applicants_applications from './applicants/applications/update-applicants-applications';
import list_applicants_applications from './applicants/applications/list-applicants-applications';
import create_applicants_notes from './applicants/notes/create-applicants-notes';
import retrieve_applicants_notes from './applicants/notes/retrieve-applicants-notes';
import list_applicants_notes from './applicants/notes/list-applicants-notes';
import create_applicants_groups from './applicants/groups/create-applicants-groups';
import retrieve_applicants_groups from './applicants/groups/retrieve-applicants-groups';
import update_applicants_groups from './applicants/groups/update-applicants-groups';
import list_applicants_groups from './applicants/groups/list-applicants-groups';
import create_groups_applicants_notes from './applicants/groups/notes/create-groups-applicants-notes';
import retrieve_groups_applicants_notes from './applicants/groups/notes/retrieve-groups-applicants-notes';
import update_groups_applicants_notes from './applicants/groups/notes/update-groups-applicants-notes';
import list_groups_applicants_notes from './applicants/groups/notes/list-groups-applicants-notes';
import create_bankaccounts from './bankaccounts/create-bankaccounts';
import retrieve_bankaccounts from './bankaccounts/retrieve-bankaccounts';
import update_bankaccounts from './bankaccounts/update-bankaccounts';
import list_bankaccounts from './bankaccounts/list-bankaccounts';
import retrieve_undeposited_funds_bankaccounts from './bankaccounts/retrieve-undeposited-funds-bankaccounts';
import create_bankaccounts_checks from './bankaccounts/checks/create-bankaccounts-checks';
import retrieve_bankaccounts_checks from './bankaccounts/checks/retrieve-bankaccounts-checks';
import update_bankaccounts_checks from './bankaccounts/checks/update-bankaccounts-checks';
import list_bankaccounts_checks from './bankaccounts/checks/list-bankaccounts-checks';
import retrieve_checks_bankaccounts_files from './bankaccounts/checks/files/retrieve-checks-bankaccounts-files';
import list_checks_bankaccounts_files from './bankaccounts/checks/files/list-checks-bankaccounts-files';
import delete_checks_bankaccounts_files from './bankaccounts/checks/files/delete-checks-bankaccounts-files';
import download_checks_bankaccounts_files from './bankaccounts/checks/files/download-checks-bankaccounts-files';
import upload_checks_bankaccounts_files from './bankaccounts/checks/files/upload-checks-bankaccounts-files';
import create_bankaccounts_deposits from './bankaccounts/deposits/create-bankaccounts-deposits';
import retrieve_bankaccounts_deposits from './bankaccounts/deposits/retrieve-bankaccounts-deposits';
import update_bankaccounts_deposits from './bankaccounts/deposits/update-bankaccounts-deposits';
import list_bankaccounts_deposits from './bankaccounts/deposits/list-bankaccounts-deposits';
import create_bankaccounts_quickdeposits from './bankaccounts/quickdeposits/create-bankaccounts-quickdeposits';
import retrieve_bankaccounts_quickdeposits from './bankaccounts/quickdeposits/retrieve-bankaccounts-quickdeposits';
import update_bankaccounts_quickdeposits from './bankaccounts/quickdeposits/update-bankaccounts-quickdeposits';
import list_bankaccounts_quickdeposits from './bankaccounts/quickdeposits/list-bankaccounts-quickdeposits';
import create_bankaccounts_reconciliations from './bankaccounts/reconciliations/create-bankaccounts-reconciliations';
import retrieve_bankaccounts_reconciliations from './bankaccounts/reconciliations/retrieve-bankaccounts-reconciliations';
import update_bankaccounts_reconciliations from './bankaccounts/reconciliations/update-bankaccounts-reconciliations';
import list_bankaccounts_reconciliations from './bankaccounts/reconciliations/list-bankaccounts-reconciliations';
import cleartransactionsrequest_bankaccounts_reconciliations from './bankaccounts/reconciliations/cleartransactionsrequest-bankaccounts-reconciliations';
import finalizerequest_bankaccounts_reconciliations from './bankaccounts/reconciliations/finalizerequest-bankaccounts-reconciliations';
import retrieve_transactions_bankaccounts_reconciliations from './bankaccounts/reconciliations/retrieve-transactions-bankaccounts-reconciliations';
import uncleartransactionsrequest_bankaccounts_reconciliations from './bankaccounts/reconciliations/uncleartransactionsrequest-bankaccounts-reconciliations';
import create_reconciliations_bankaccounts_balances from './bankaccounts/reconciliations/balances/create-reconciliations-bankaccounts-balances';
import list_reconciliations_bankaccounts_balances from './bankaccounts/reconciliations/balances/list-reconciliations-bankaccounts-balances';
import retrieve_bankaccounts_transactions from './bankaccounts/transactions/retrieve-bankaccounts-transactions';
import list_bankaccounts_transactions from './bankaccounts/transactions/list-bankaccounts-transactions';
import create_bankaccounts_transfers from './bankaccounts/transfers/create-bankaccounts-transfers';
import retrieve_bankaccounts_transfers from './bankaccounts/transfers/retrieve-bankaccounts-transfers';
import update_bankaccounts_transfers from './bankaccounts/transfers/update-bankaccounts-transfers';
import list_bankaccounts_transfers from './bankaccounts/transfers/list-bankaccounts-transfers';
import create_bankaccounts_withdrawals from './bankaccounts/withdrawals/create-bankaccounts-withdrawals';
import retrieve_bankaccounts_withdrawals from './bankaccounts/withdrawals/retrieve-bankaccounts-withdrawals';
import update_bankaccounts_withdrawals from './bankaccounts/withdrawals/update-bankaccounts-withdrawals';
import list_bankaccounts_withdrawals from './bankaccounts/withdrawals/list-bankaccounts-withdrawals';
import create_bills from './bills/create-bills';
import retrieve_bills from './bills/retrieve-bills';
import update_bills from './bills/update-bills';
import list_bills from './bills/list-bills';
import retrieve_bills_files from './bills/files/retrieve-bills-files';
import list_bills_files from './bills/files/list-bills-files';
import delete_bills_files from './bills/files/delete-bills-files';
import download_bills_files from './bills/files/download-bills-files';
import upload_bills_files from './bills/files/upload-bills-files';
import create_bills_payments from './bills/payments/create-bills-payments';
import retrieve_bills_payments from './bills/payments/retrieve-bills-payments';
import list_bills_payments from './bills/payments/list-bills-payments';
import create_multiple_bills_payments from './bills/payments/create-multiple-bills-payments';
import create_budgets from './budgets/create-budgets';
import retrieve_budgets from './budgets/retrieve-budgets';
import update_budgets from './budgets/update-budgets';
import list_budgets from './budgets/list-budgets';
import retrieve_clientleads from './clientleads/retrieve-clientleads';
import list_clientleads from './clientleads/list-clientleads';
import create_communications_announcements from './communications/announcements/create-communications-announcements';
import retrieve_communications_announcements from './communications/announcements/retrieve-communications-announcements';
import list_communications_announcements from './communications/announcements/list-communications-announcements';
import expire_communications_announcements from './communications/announcements/expire-communications-announcements';
import retrieve_properties_communications_announcements from './communications/announcements/retrieve-properties-communications-announcements';
import retrieve_communications_emails from './communications/emails/retrieve-communications-emails';
import list_communications_emails from './communications/emails/list-communications-emails';
import retrieve_recipients_communications_emails from './communications/emails/retrieve-recipients-communications-emails';
import send_communications_emails from './communications/emails/send-communications-emails';
import create_communications_phonelogs from './communications/phonelogs/create-communications-phonelogs';
import retrieve_communications_phonelogs from './communications/phonelogs/retrieve-communications-phonelogs';
import update_communications_phonelogs from './communications/phonelogs/update-communications-phonelogs';
import list_communications_phonelogs from './communications/phonelogs/list-communications-phonelogs';
import retrieve_communications_templates from './communications/templates/retrieve-communications-templates';
import list_communications_templates from './communications/templates/list-communications-templates';
import list_generalledger from './generalledger/list-generalledger';
import create_generalledger_journalentries from './generalledger/journalentries/create-generalledger-journalentries';
import update_generalledger_journalentries from './generalledger/journalentries/update-generalledger-journalentries';
import retrieve_generalledger_transactions from './generalledger/transactions/retrieve-generalledger-transactions';
import list_generalledger_transactions from './generalledger/transactions/list-generalledger-transactions';
import create_glaccounts from './glaccounts/create-glaccounts';
import retrieve_glaccounts from './glaccounts/retrieve-glaccounts';
import update_glaccounts from './glaccounts/update-glaccounts';
import list_glaccounts from './glaccounts/list-glaccounts';
import list_balances_glaccounts from './glaccounts/list-balances-glaccounts';
import create_propertygroups from './propertygroups/create-propertygroups';
import retrieve_propertygroups from './propertygroups/retrieve-propertygroups';
import update_propertygroups from './propertygroups/update-propertygroups';
import list_propertygroups from './propertygroups/list-propertygroups';
import list_resident_center_users from './resident-center-users/list-resident-center-users';
import retrieve_retailcashusers from './retailcashusers/retrieve-retailcashusers';
import update_retailcashusers from './retailcashusers/update-retailcashusers';
import list_retailcashusers from './retailcashusers/list-retailcashusers';
import retrieve_tasks from './tasks/retrieve-tasks';
import list_tasks from './tasks/list-tasks';
import retrieve_tasks_history from './tasks/history/retrieve-tasks-history';
import update_tasks_history from './tasks/history/update-tasks-history';
import list_tasks_history from './tasks/history/list-tasks-history';
import retrieve_history_tasks_files from './tasks/history/files/retrieve-history-tasks-files';
import list_history_tasks_files from './tasks/history/files/list-history-tasks-files';
import delete_history_tasks_files from './tasks/history/files/delete-history-tasks-files';
import download_request_history_tasks_files from './tasks/history/files/download-request-history-tasks-files';
import upload_request_history_tasks_files from './tasks/history/files/upload-request-history-tasks-files';
import create_tasks_categories from './tasks/categories/create-tasks-categories';
import retrieve_tasks_categories from './tasks/categories/retrieve-tasks-categories';
import update_tasks_categories from './tasks/categories/update-tasks-categories';
import list_tasks_categories from './tasks/categories/list-tasks-categories';
import create_tasks_contactrequests from './tasks/contactrequests/create-tasks-contactrequests';
import retrieve_tasks_contactrequests from './tasks/contactrequests/retrieve-tasks-contactrequests';
import update_tasks_contactrequests from './tasks/contactrequests/update-tasks-contactrequests';
import list_tasks_contactrequests from './tasks/contactrequests/list-tasks-contactrequests';
import create_tasks_rentalownerrequests from './tasks/rentalownerrequests/create-tasks-rentalownerrequests';
import retrieve_tasks_rentalownerrequests from './tasks/rentalownerrequests/retrieve-tasks-rentalownerrequests';
import update_tasks_rentalownerrequests from './tasks/rentalownerrequests/update-tasks-rentalownerrequests';
import list_tasks_rentalownerrequests from './tasks/rentalownerrequests/list-tasks-rentalownerrequests';
import retrieve_rentalownerrequests_tasks_contributiondata from './tasks/rentalownerrequests/contributiondata/retrieve-rentalownerrequests-tasks-contributiondata';
import update_rentalownerrequests_tasks_contributiondata from './tasks/rentalownerrequests/contributiondata/update-rentalownerrequests-tasks-contributiondata';
import create_tasks_residentrequests from './tasks/residentrequests/create-tasks-residentrequests';
import retrieve_tasks_residentrequests from './tasks/residentrequests/retrieve-tasks-residentrequests';
import update_tasks_residentrequests from './tasks/residentrequests/update-tasks-residentrequests';
import list_tasks_residentrequests from './tasks/residentrequests/list-tasks-residentrequests';
import create_tasks_todorequests from './tasks/todorequests/create-tasks-todorequests';
import retrieve_tasks_todorequests from './tasks/todorequests/retrieve-tasks-todorequests';
import update_tasks_todorequests from './tasks/todorequests/update-tasks-todorequests';
import list_tasks_todorequests from './tasks/todorequests/list-tasks-todorequests';
import create_vendors from './vendors/create-vendors';
import retrieve_vendors from './vendors/retrieve-vendors';
import update_vendors from './vendors/update-vendors';
import list_vendors from './vendors/list-vendors';
import retrieve_transactions_vendors from './vendors/retrieve-transactions-vendors';
import create_vendors_credits from './vendors/credits/create-vendors-credits';
import retrieve_vendors_credits from './vendors/credits/retrieve-vendors-credits';
import create_vendors_notes from './vendors/notes/create-vendors-notes';
import retrieve_vendors_notes from './vendors/notes/retrieve-vendors-notes';
import update_vendors_notes from './vendors/notes/update-vendors-notes';
import list_vendors_notes from './vendors/notes/list-vendors-notes';
import create_vendors_refunds from './vendors/refunds/create-vendors-refunds';
import retrieve_vendors_refunds from './vendors/refunds/retrieve-vendors-refunds';
import create_vendors_categories from './vendors/categories/create-vendors-categories';
import retrieve_vendors_categories from './vendors/categories/retrieve-vendors-categories';
import update_vendors_categories from './vendors/categories/update-vendors-categories';
import list_vendors_categories from './vendors/categories/list-vendors-categories';
import create_workorders from './workorders/create-workorders';
import retrieve_workorders from './workorders/retrieve-workorders';
import update_workorders from './workorders/update-workorders';
import list_workorders from './workorders/list-workorders';

export const endpoints: Endpoint[] = [];

function addEndpoint(endpoint: Endpoint) {
  endpoints.push(endpoint);
}

addEndpoint(create_auto_allocated_payment_applications);
addEndpoint(create_payment_reversal_applications);
addEndpoint(list_outstanding_balances_applications);
addEndpoint(retrieve_applications_transactions);
addEndpoint(list_applications_transactions);
addEndpoint(create_applications_charges);
addEndpoint(retrieve_applications_charges);
addEndpoint(update_applications_charges);
addEndpoint(list_applications_charges);
addEndpoint(create_applications_payments);
addEndpoint(update_applications_payments);
addEndpoint(create_applications_refunds);
addEndpoint(retrieve_applications_refunds);
addEndpoint(create_associations);
addEndpoint(retrieve_associations);
addEndpoint(update_associations);
addEndpoint(list_associations);
addEndpoint(inactivate_associations);
addEndpoint(list_bank_lockbox_data_associations);
addEndpoint(reactivate_associations);
addEndpoint(create_associations_ownershipaccounts);
addEndpoint(retrieve_associations_ownershipaccounts);
addEndpoint(update_associations_ownershipaccounts);
addEndpoint(list_associations_ownershipaccounts);
addEndpoint(autoallocatedpayments_associations_ownershipaccounts);
addEndpoint(credits_associations_ownershipaccounts);
addEndpoint(retrieve_outstandingbalances_associations_ownershipaccounts);
addEndpoint(retrieve_ownershipaccounts_associations_transactions);
addEndpoint(list_ownershipaccounts_associations_transactions);
addEndpoint(create_ownershipaccounts_associations_architecturalrequests);
addEndpoint(retrieve_ownershipaccounts_associations_architecturalrequests);
addEndpoint(list_ownershipaccounts_associations_architecturalrequests);
addEndpoint(retrieve_architecturalrequests_ownershipaccounts_associations_files);
addEndpoint(list_architecturalrequests_ownershipaccounts_associations_files);
addEndpoint(downloadrequests_architecturalrequests_ownershipaccounts_associations_files);
addEndpoint(uploadrequests_architecturalrequests_ownershipaccounts_associations_files);
addEndpoint(create_ownershipaccounts_associations_charges);
addEndpoint(retrieve_ownershipaccounts_associations_charges);
addEndpoint(update_ownershipaccounts_associations_charges);
addEndpoint(list_ownershipaccounts_associations_charges);
addEndpoint(create_ownershipaccounts_associations_payments);
addEndpoint(update_ownershipaccounts_associations_payments);
addEndpoint(create_ownershipaccounts_associations_refunds);
addEndpoint(retrieve_ownershipaccounts_associations_refunds);
addEndpoint(create_ownershipaccounts_associations_applieddeposits);
addEndpoint(update_ownershipaccounts_associations_applieddeposits);
addEndpoint(list_ownershipaccounts_associations_recurringtransactions);
addEndpoint(create_ownershipaccounts_associations_notes);
addEndpoint(retrieve_ownershipaccounts_associations_notes);
addEndpoint(update_ownershipaccounts_associations_notes);
addEndpoint(list_ownershipaccounts_associations_notes);
addEndpoint(list_ownershipaccounts_associations_partialpaymentsettings);
addEndpoint(patch_all_ownershipaccounts_associations_partialpaymentsettings);
addEndpoint(create_ownershipaccounts_associations_recurringcharges);
addEndpoint(retrieve_ownershipaccounts_associations_recurringcharges);
addEndpoint(create_ownershipaccounts_associations_recurringcredits);
addEndpoint(retrieve_ownershipaccounts_associations_recurringcredits);
addEndpoint(create_ownershipaccounts_associations_recurringpayments);
addEndpoint(retrieve_ownershipaccounts_associations_recurringpayments);
addEndpoint(create_associations_units);
addEndpoint(retrieve_associations_units);
addEndpoint(update_associations_units);
addEndpoint(list_associations_units);
addEndpoint(create_units_associations_notes);
addEndpoint(retrieve_units_associations_notes);
addEndpoint(update_units_associations_notes);
addEndpoint(list_units_associations_notes);
addEndpoint(create_associations_owners);
addEndpoint(retrieve_associations_owners);
addEndpoint(update_associations_owners);
addEndpoint(list_associations_owners);
addEndpoint(create_owners_associations_notes);
addEndpoint(retrieve_owners_associations_notes);
addEndpoint(update_owners_associations_notes);
addEndpoint(list_owners_associations_notes);
addEndpoint(retrieve_owners_associations_units);
addEndpoint(update_owners_associations_units);
addEndpoint(list_owners_associations_units);
addEndpoint(create_associations_tenants);
addEndpoint(retrieve_associations_tenants);
addEndpoint(update_associations_tenants);
addEndpoint(list_associations_tenants);
addEndpoint(create_tenants_associations_notes);
addEndpoint(retrieve_tenants_associations_notes);
addEndpoint(update_tenants_associations_notes);
addEndpoint(list_tenants_associations_notes);
addEndpoint(create_associations_boardmembers);
addEndpoint(retrieve_associations_boardmembers);
addEndpoint(update_associations_boardmembers);
addEndpoint(list_associations_boardmembers);
addEndpoint(delete_associations_boardmembers);
addEndpoint(retrieve_associations_epaysettings);
addEndpoint(update_associations_epaysettings);
addEndpoint(list_associations_meterreadings);
addEndpoint(update_meterreadings_associations_summary);
addEndpoint(list_meterreadings_associations_summary);
addEndpoint(delete_meterreadings_associations_summary);
addEndpoint(create_associations_notes);
addEndpoint(retrieve_associations_notes);
addEndpoint(update_associations_notes);
addEndpoint(list_associations_notes);
addEndpoint(update_associations_vendors);
addEndpoint(list_associations_vendors);
addEndpoint(create_associations_appliances);
addEndpoint(retrieve_associations_appliances);
addEndpoint(update_associations_appliances);
addEndpoint(list_associations_appliances);
addEndpoint(delete_associations_appliances);
addEndpoint(create_appliances_associations_servicehistory);
addEndpoint(retrieve_appliances_associations_servicehistory);
addEndpoint(list_appliances_associations_servicehistory);
addEndpoint(retrieve_files);
addEndpoint(update_files);
addEndpoint(list_files);
addEndpoint(create_upload_request_files);
addEndpoint(request_download_files);
addEndpoint(retrieve_files_sharing);
addEndpoint(update_files_sharing);
addEndpoint(create_files_categories);
addEndpoint(retrieve_files_categories);
addEndpoint(update_files_categories);
addEndpoint(list_files_categories);
addEndpoint(create_leases);
addEndpoint(retrieve_leases);
addEndpoint(update_leases);
addEndpoint(list_leases);
addEndpoint(create_autoallocated_payment_leases);
addEndpoint(create_credit_leases);
addEndpoint(create_payment_reversal_leases);
addEndpoint(list_outstanding_balances_leases);
addEndpoint(list_renewal_history_leases);
addEndpoint(retrieve_leases_transactions);
addEndpoint(list_leases_transactions);
addEndpoint(create_leases_charges);
addEndpoint(retrieve_leases_charges);
addEndpoint(update_leases_charges);
addEndpoint(list_leases_charges);
addEndpoint(create_leases_moveouts);
addEndpoint(retrieve_leases_moveouts);
addEndpoint(list_leases_moveouts);
addEndpoint(delete_leases_moveouts);
addEndpoint(create_leases_payments);
addEndpoint(update_leases_payments);
addEndpoint(create_leases_notes);
addEndpoint(retrieve_leases_notes);
addEndpoint(update_leases_notes);
addEndpoint(list_leases_notes);
addEndpoint(create_leases_refunds);
addEndpoint(retrieve_leases_refunds);
addEndpoint(create_leases_renewals);
addEndpoint(retrieve_leases_renewals);
addEndpoint(list_leases_renewals);
addEndpoint(list_upcoming_leases_renewals);
addEndpoint(create_leases_applieddeposits);
addEndpoint(update_leases_applieddeposits);
addEndpoint(list_leases_recurringtransactions);
addEndpoint(list_all_leases_recurringtransactions);
addEndpoint(retrieve_leases_epaysettings);
addEndpoint(update_leases_epaysettings);
addEndpoint(retrieve_leases_partialpaymentsettings);
addEndpoint(update_leases_partialpaymentsettings);
addEndpoint(create_leases_recurringcharges);
addEndpoint(retrieve_leases_recurringcharges);
addEndpoint(create_leases_recurringcredits);
addEndpoint(retrieve_leases_recurringcredits);
addEndpoint(create_leases_recurringpayments);
addEndpoint(retrieve_leases_recurringpayments);
addEndpoint(create_leases_rent);
addEndpoint(retrieve_leases_rent);
addEndpoint(update_leases_rent);
addEndpoint(retrieve_all_leases_rent);
addEndpoint(retrieve_leases_rentersinsurance);
addEndpoint(retrieve_all_leases_rentersinsurance);
addEndpoint(create_leases_tenants);
addEndpoint(retrieve_leases_tenants);
addEndpoint(update_leases_tenants);
addEndpoint(retrieve_all_leases_tenants);
addEndpoint(create_tenants_leases_notes);
addEndpoint(retrieve_tenants_leases_notes);
addEndpoint(update_tenants_leases_notes);
addEndpoint(retrieve_all_tenants_leases_notes);
addEndpoint(create_rentals);
addEndpoint(retrieve_rentals);
addEndpoint(update_rentals);
addEndpoint(list_rentals);
addEndpoint(inactivate_rentals);
addEndpoint(reactivate_rentals);
addEndpoint(create_rentals_units);
addEndpoint(retrieve_rentals_units);
addEndpoint(update_rentals_units);
addEndpoint(list_rentals_units);
addEndpoint(retrieve_listings_rentals_units);
addEndpoint(create_units_rentals_listing);
addEndpoint(list_units_rentals_listing);
addEndpoint(delete_all_units_rentals_listing);
addEndpoint(create_units_rentals_listingcontacts);
addEndpoint(retrieve_units_rentals_listingcontacts);
addEndpoint(update_units_rentals_listingcontacts);
addEndpoint(list_units_rentals_listingcontacts);
addEndpoint(create_units_rentals_amenities);
addEndpoint(list_units_rentals_amenities);
addEndpoint(retrieve_units_rentals_images);
addEndpoint(update_units_rentals_images);
addEndpoint(list_units_rentals_images);
addEndpoint(delete_units_rentals_images);
addEndpoint(downloadrequests_units_rentals_images);
addEndpoint(update_order_units_rentals_images);
addEndpoint(uploadrequests_units_rentals_images);
addEndpoint(videolinkrequests_units_rentals_images);
addEndpoint(create_units_rentals_notes);
addEndpoint(retrieve_units_rentals_notes);
addEndpoint(update_units_rentals_notes);
addEndpoint(list_units_rentals_notes);
addEndpoint(create_rentals_vendors);
addEndpoint(list_rentals_vendors);
addEndpoint(create_rentals_amenities);
addEndpoint(list_rentals_amenities);
addEndpoint(create_rentals_epaysettings);
addEndpoint(list_rentals_epaysettings);
addEndpoint(retrieve_rentals_images);
addEndpoint(update_rentals_images);
addEndpoint(list_rentals_images);
addEndpoint(delete_rentals_images);
addEndpoint(downloadrequests_rentals_images);
addEndpoint(update_order_rentals_images);
addEndpoint(uploadrequests_rentals_images);
addEndpoint(videolinkrequests_rentals_images);
addEndpoint(list_rentals_meterreadings);
addEndpoint(create_meterreadings_rentals_summary);
addEndpoint(list_meterreadings_rentals_summary);
addEndpoint(delete_all_meterreadings_rentals_summary);
addEndpoint(create_rentals_notes);
addEndpoint(retrieve_rentals_notes);
addEndpoint(update_rentals_notes);
addEndpoint(list_rentals_notes);
addEndpoint(create_rentals_appliances);
addEndpoint(retrieve_rentals_appliances);
addEndpoint(update_rentals_appliances);
addEndpoint(list_rentals_appliances);
addEndpoint(delete_rentals_appliances);
addEndpoint(create_appliances_rentals_servicehistory);
addEndpoint(retrieve_appliances_rentals_servicehistory);
addEndpoint(list_appliances_rentals_servicehistory);
addEndpoint(create_rentals_owners);
addEndpoint(retrieve_rentals_owners);
addEndpoint(update_rentals_owners);
addEndpoint(list_rentals_owners);
addEndpoint(create_owners_rentals_notes);
addEndpoint(retrieve_owners_rentals_notes);
addEndpoint(update_owners_rentals_notes);
addEndpoint(list_owners_rentals_notes);
addEndpoint(retrieve_users);
addEndpoint(list_users);
addEndpoint(retrieve_userroles);
addEndpoint(list_userroles);
addEndpoint(retrieve_account_administration);
addEndpoint(retrieve_accounting_lock_periods_administration);
addEndpoint(retrieve_residentsettings_administration_partialpaymentsettings);
addEndpoint(update_residentsettings_administration_partialpaymentsettings);
addEndpoint(create_applicants);
addEndpoint(retrieve_applicants);
addEndpoint(update_applicants);
addEndpoint(list_applicants);
addEndpoint(retrieve_applicants_applications);
addEndpoint(update_applicants_applications);
addEndpoint(list_applicants_applications);
addEndpoint(create_applicants_notes);
addEndpoint(retrieve_applicants_notes);
addEndpoint(list_applicants_notes);
addEndpoint(create_applicants_groups);
addEndpoint(retrieve_applicants_groups);
addEndpoint(update_applicants_groups);
addEndpoint(list_applicants_groups);
addEndpoint(create_groups_applicants_notes);
addEndpoint(retrieve_groups_applicants_notes);
addEndpoint(update_groups_applicants_notes);
addEndpoint(list_groups_applicants_notes);
addEndpoint(create_bankaccounts);
addEndpoint(retrieve_bankaccounts);
addEndpoint(update_bankaccounts);
addEndpoint(list_bankaccounts);
addEndpoint(retrieve_undeposited_funds_bankaccounts);
addEndpoint(create_bankaccounts_checks);
addEndpoint(retrieve_bankaccounts_checks);
addEndpoint(update_bankaccounts_checks);
addEndpoint(list_bankaccounts_checks);
addEndpoint(retrieve_checks_bankaccounts_files);
addEndpoint(list_checks_bankaccounts_files);
addEndpoint(delete_checks_bankaccounts_files);
addEndpoint(download_checks_bankaccounts_files);
addEndpoint(upload_checks_bankaccounts_files);
addEndpoint(create_bankaccounts_deposits);
addEndpoint(retrieve_bankaccounts_deposits);
addEndpoint(update_bankaccounts_deposits);
addEndpoint(list_bankaccounts_deposits);
addEndpoint(create_bankaccounts_quickdeposits);
addEndpoint(retrieve_bankaccounts_quickdeposits);
addEndpoint(update_bankaccounts_quickdeposits);
addEndpoint(list_bankaccounts_quickdeposits);
addEndpoint(create_bankaccounts_reconciliations);
addEndpoint(retrieve_bankaccounts_reconciliations);
addEndpoint(update_bankaccounts_reconciliations);
addEndpoint(list_bankaccounts_reconciliations);
addEndpoint(cleartransactionsrequest_bankaccounts_reconciliations);
addEndpoint(finalizerequest_bankaccounts_reconciliations);
addEndpoint(retrieve_transactions_bankaccounts_reconciliations);
addEndpoint(uncleartransactionsrequest_bankaccounts_reconciliations);
addEndpoint(create_reconciliations_bankaccounts_balances);
addEndpoint(list_reconciliations_bankaccounts_balances);
addEndpoint(retrieve_bankaccounts_transactions);
addEndpoint(list_bankaccounts_transactions);
addEndpoint(create_bankaccounts_transfers);
addEndpoint(retrieve_bankaccounts_transfers);
addEndpoint(update_bankaccounts_transfers);
addEndpoint(list_bankaccounts_transfers);
addEndpoint(create_bankaccounts_withdrawals);
addEndpoint(retrieve_bankaccounts_withdrawals);
addEndpoint(update_bankaccounts_withdrawals);
addEndpoint(list_bankaccounts_withdrawals);
addEndpoint(create_bills);
addEndpoint(retrieve_bills);
addEndpoint(update_bills);
addEndpoint(list_bills);
addEndpoint(retrieve_bills_files);
addEndpoint(list_bills_files);
addEndpoint(delete_bills_files);
addEndpoint(download_bills_files);
addEndpoint(upload_bills_files);
addEndpoint(create_bills_payments);
addEndpoint(retrieve_bills_payments);
addEndpoint(list_bills_payments);
addEndpoint(create_multiple_bills_payments);
addEndpoint(create_budgets);
addEndpoint(retrieve_budgets);
addEndpoint(update_budgets);
addEndpoint(list_budgets);
addEndpoint(retrieve_clientleads);
addEndpoint(list_clientleads);
addEndpoint(create_communications_announcements);
addEndpoint(retrieve_communications_announcements);
addEndpoint(list_communications_announcements);
addEndpoint(expire_communications_announcements);
addEndpoint(retrieve_properties_communications_announcements);
addEndpoint(retrieve_communications_emails);
addEndpoint(list_communications_emails);
addEndpoint(retrieve_recipients_communications_emails);
addEndpoint(send_communications_emails);
addEndpoint(create_communications_phonelogs);
addEndpoint(retrieve_communications_phonelogs);
addEndpoint(update_communications_phonelogs);
addEndpoint(list_communications_phonelogs);
addEndpoint(retrieve_communications_templates);
addEndpoint(list_communications_templates);
addEndpoint(list_generalledger);
addEndpoint(create_generalledger_journalentries);
addEndpoint(update_generalledger_journalentries);
addEndpoint(retrieve_generalledger_transactions);
addEndpoint(list_generalledger_transactions);
addEndpoint(create_glaccounts);
addEndpoint(retrieve_glaccounts);
addEndpoint(update_glaccounts);
addEndpoint(list_glaccounts);
addEndpoint(list_balances_glaccounts);
addEndpoint(create_propertygroups);
addEndpoint(retrieve_propertygroups);
addEndpoint(update_propertygroups);
addEndpoint(list_propertygroups);
addEndpoint(list_resident_center_users);
addEndpoint(retrieve_retailcashusers);
addEndpoint(update_retailcashusers);
addEndpoint(list_retailcashusers);
addEndpoint(retrieve_tasks);
addEndpoint(list_tasks);
addEndpoint(retrieve_tasks_history);
addEndpoint(update_tasks_history);
addEndpoint(list_tasks_history);
addEndpoint(retrieve_history_tasks_files);
addEndpoint(list_history_tasks_files);
addEndpoint(delete_history_tasks_files);
addEndpoint(download_request_history_tasks_files);
addEndpoint(upload_request_history_tasks_files);
addEndpoint(create_tasks_categories);
addEndpoint(retrieve_tasks_categories);
addEndpoint(update_tasks_categories);
addEndpoint(list_tasks_categories);
addEndpoint(create_tasks_contactrequests);
addEndpoint(retrieve_tasks_contactrequests);
addEndpoint(update_tasks_contactrequests);
addEndpoint(list_tasks_contactrequests);
addEndpoint(create_tasks_rentalownerrequests);
addEndpoint(retrieve_tasks_rentalownerrequests);
addEndpoint(update_tasks_rentalownerrequests);
addEndpoint(list_tasks_rentalownerrequests);
addEndpoint(retrieve_rentalownerrequests_tasks_contributiondata);
addEndpoint(update_rentalownerrequests_tasks_contributiondata);
addEndpoint(create_tasks_residentrequests);
addEndpoint(retrieve_tasks_residentrequests);
addEndpoint(update_tasks_residentrequests);
addEndpoint(list_tasks_residentrequests);
addEndpoint(create_tasks_todorequests);
addEndpoint(retrieve_tasks_todorequests);
addEndpoint(update_tasks_todorequests);
addEndpoint(list_tasks_todorequests);
addEndpoint(create_vendors);
addEndpoint(retrieve_vendors);
addEndpoint(update_vendors);
addEndpoint(list_vendors);
addEndpoint(retrieve_transactions_vendors);
addEndpoint(create_vendors_credits);
addEndpoint(retrieve_vendors_credits);
addEndpoint(create_vendors_notes);
addEndpoint(retrieve_vendors_notes);
addEndpoint(update_vendors_notes);
addEndpoint(list_vendors_notes);
addEndpoint(create_vendors_refunds);
addEndpoint(retrieve_vendors_refunds);
addEndpoint(create_vendors_categories);
addEndpoint(retrieve_vendors_categories);
addEndpoint(update_vendors_categories);
addEndpoint(list_vendors_categories);
addEndpoint(create_workorders);
addEndpoint(retrieve_workorders);
addEndpoint(update_workorders);
addEndpoint(list_workorders);

export type Filter = {
  type: 'resource' | 'operation' | 'tag' | 'tool';
  op: 'include' | 'exclude';
  value: string;
};

export function query(filters: Filter[], endpoints: Endpoint[]): Endpoint[] {
  const allExcludes = filters.length > 0 && filters.every((filter) => filter.op === 'exclude');
  const unmatchedFilters = new Set(filters);

  const filtered = endpoints.filter((endpoint: Endpoint) => {
    let included = false || allExcludes;

    for (const filter of filters) {
      if (match(filter, endpoint)) {
        unmatchedFilters.delete(filter);
        included = filter.op === 'include';
      }
    }

    return included;
  });

  // Check if any filters didn't match
  const unmatched = Array.from(unmatchedFilters).filter((f) => f.type === 'tool' || f.type === 'resource');
  if (unmatched.length > 0) {
    throw new Error(
      `The following filters did not match any endpoints: ${unmatched
        .map((f) => `${f.type}=${f.value}`)
        .join(', ')}`,
    );
  }

  return filtered;
}

function match({ type, value }: Filter, endpoint: Endpoint): boolean {
  switch (type) {
    case 'resource': {
      const regexStr = '^' + normalizeResource(value).replace(/\*/g, '.*') + '$';
      const regex = new RegExp(regexStr);
      return regex.test(normalizeResource(endpoint.metadata.resource));
    }
    case 'operation':
      return endpoint.metadata.operation === value;
    case 'tag':
      return endpoint.metadata.tags.includes(value);
    case 'tool':
      return endpoint.tool.name === value;
  }
}

function normalizeResource(resource: string): string {
  return resource.toLowerCase().replace(/[^a-z.*\-_]*/g, '');
}
