// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { asTextContentResult } from 'wpm-mcp-server-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Metadata } from '../../';
import WpmMcpServer from 'wpm-mcp-server';

export const metadata: Metadata = {
  resource: 'rentals.units',
  operation: 'write',
  tags: [],
  httpMethod: 'put',
  httpPath: '/v1/rentals/units/{unitId}',
  operationId: 'ExternalApiRentalUnits_UpdateRentalUnit',
};

export const tool: Tool = {
  name: 'update_rentals_units',
  description:
    'Updates a rental unit.\r\n\r\n\r\n<strong>NOTE:</strong> Any field not included in the update request will be set to either an empty string or `null` in the database depending on the field definition. \r\nThe recommended workflow to ensure no data is inadvertently overwritten is to execute a `GET` request for the resource you\'re about to update and then use this response to fill any of the fields that are not being updated.\r\n\r\n\r\n<h4>Required permission(s):</h4><span class="permissionBlock">Rentals > Rental properties and units</span> - `View` `Edit`',
  inputSchema: {
    type: 'object',
    properties: {
      unitId: {
        type: 'integer',
      },
      Address: {
        type: 'object',
        description: 'Address.',
        properties: {
          AddressLine1: {
            type: 'string',
            description:
              'Address line 1 (e.g., street, PO Box, or company name). This value cannot exceed 100 characters.',
          },
          Country: {
            type: 'string',
            description: 'Country. Must be a valid `Country` enumeration value.',
            enum: [
              'Afghanistan',
              'Akrotiri',
              'Albania',
              'Algeria',
              'AmericanSamoa',
              'Andorra',
              'Angola',
              'Anguilla',
              'Antarctica',
              'AntiguaandBarbuda',
              'Argentina',
              'Armenia',
              'Aruba',
              'AshmoreandCartierIslands',
              'Australia',
              'Austria',
              'Azerbaijan',
              'Bahamas',
              'Bahrain',
              'Bangladesh',
              'Barbados',
              'BassasdaIndia',
              'Belarus',
              'Belgium',
              'Belize',
              'Benin',
              'Bermuda',
              'Bhutan',
              'Bolivia',
              'BosniaandHerzegovina',
              'Botswana',
              'BouvetIsland',
              'Brazil',
              'BritishIndianOceanTerritory',
              'BritishVirginIslands',
              'Brunei',
              'Bulgaria',
              'BurkinaFaso',
              'Burma',
              'Burundi',
              'Cambodia',
              'Cameroon',
              'Canada',
              'CapeVerde',
              'CaymanIslands',
              'CentralAfricanRepublic',
              'Chad',
              'Chile',
              'China',
              'ChristmasIsland',
              'ClippertonIsland',
              'CocosIslands',
              'Colombia',
              'Comoros',
              'DemocraticRepublicOfTheCongo',
              'RepublicOfTheCongo',
              'CookIslands',
              'CoralSeaIslands',
              'CostaRica',
              'CotedIvoire',
              'Croatia',
              'Cuba',
              'Cyprus',
              'CzechRepublic',
              'Denmark',
              'Dhekelia',
              'Djibouti',
              'Dominica',
              'DominicanRepublic',
              'Ecuador',
              'Egypt',
              'ElSalvador',
              'EquatorialGuinea',
              'Eritrea',
              'Estonia',
              'Ethiopia',
              'EuropaIsland',
              'FalklandIslands',
              'FaroeIslands',
              'Fiji',
              'Finland',
              'France',
              'FrenchGuiana',
              'FrenchPolynesia',
              'FrenchSouthernandAntarcticLands',
              'Gabon',
              'Gambia',
              'GazaStrip',
              'Georgia',
              'Germany',
              'Ghana',
              'Gibraltar',
              'GloriosoIslands',
              'Greece',
              'Greenland',
              'Grenada',
              'Guadeloupe',
              'Guam',
              'Guatemala',
              'Guernsey',
              'Guinea',
              'GuineaBissau',
              'Guyana',
              'Haiti',
              'HeardIslandandMcDonaldIslands',
              'VaticanCity',
              'Honduras',
              'HongKong',
              'Hungary',
              'Iceland',
              'India',
              'Indonesia',
              'Iran',
              'Iraq',
              'Ireland',
              'IsleofMan',
              'Israel',
              'Italy',
              'Jamaica',
              'JanMayen',
              'Japan',
              'Jersey',
              'Jordan',
              'JuandeNovaIsland',
              'Kazakhstan',
              'Kenya',
              'Kiribati',
              'NorthKorea',
              'SouthKorea',
              'Kuwait',
              'Kyrgyzstan',
              'Laos',
              'Latvia',
              'Lebanon',
              'Lesotho',
              'Liberia',
              'Libya',
              'Liechtenstein',
              'Lithuania',
              'Luxembourg',
              'Macau',
              'Macedonia',
              'Madagascar',
              'Malawi',
              'Malaysia',
              'Maldives',
              'Mali',
              'Malta',
              'MarshallIslands',
              'Martinique',
              'Mauritania',
              'Mauritius',
              'Mayotte',
              'Mexico',
              'Micronesia',
              'Moldova',
              'Monaco',
              'Mongolia',
              'Montserrat',
              'Morocco',
              'Mozambique',
              'Namibia',
              'Nauru',
              'NavassaIsland',
              'Nepal',
              'Netherlands',
              'NetherlandsAntilles',
              'NewCaledonia',
              'NewZealand',
              'Nicaragua',
              'Niger',
              'Nigeria',
              'Niue',
              'NorfolkIsland',
              'NorthernMarianaIslands',
              'Norway',
              'Oman',
              'Pakistan',
              'Palau',
              'Panama',
              'PapuaNewGuinea',
              'ParacelIslands',
              'Paraguay',
              'Peru',
              'Philippines',
              'PitcairnIslands',
              'Poland',
              'Portugal',
              'PuertoRico',
              'Qatar',
              'Reunion',
              'Romania',
              'Russia',
              'Rwanda',
              'SaintHelena',
              'SaintKittsandNevis',
              'SaintLucia',
              'SaintPierreandMiquelon',
              'SaintVincentandtheGrenadines',
              'Samoa',
              'SanMarino',
              'SaoTomeandPrincipe',
              'SaudiArabia',
              'Senegal',
              'SerbiaandMontenegro',
              'Seychelles',
              'SierraLeone',
              'Singapore',
              'Slovakia',
              'Slovenia',
              'SolomonIslands',
              'Somalia',
              'SouthAfrica',
              'SouthGeorgiaandtheSouthSandwichIslands',
              'Spain',
              'SpratlyIslands',
              'SriLanka',
              'Sudan',
              'Suriname',
              'Svalbard',
              'Swaziland',
              'Sweden',
              'Switzerland',
              'Syria',
              'Taiwan',
              'Tajikistan',
              'Tanzania',
              'Thailand',
              'TimorLeste',
              'Togo',
              'Tokelau',
              'Tonga',
              'TrinidadandTobago',
              'TromelinIsland',
              'Tunisia',
              'Turkey',
              'Turkmenistan',
              'TurksandCaicosIslands',
              'Tuvalu',
              'Uganda',
              'Ukraine',
              'UnitedArabEmirates',
              'UnitedKingdom',
              'UnitedStates',
              'Uruguay',
              'Uzbekistan',
              'Vanuatu',
              'Venezuela',
              'Vietnam',
              'VirginIslands',
              'WakeIsland',
              'WallisandFutuna',
              'WestBank',
              'WesternSahara',
              'Yemen',
              'Zambia',
              'Zimbabwe',
            ],
          },
          PostalCode: {
            type: 'string',
            description: 'ZIP or postal code.',
          },
          AddressLine2: {
            type: 'string',
            description:
              'Address line 2 (e.g., apartment, suite, unit, or building). This value cannot exceed 100 characters.',
          },
          AddressLine3: {
            type: 'string',
            description: 'Address line 3.  This value cannot exceed 100 characters.',
          },
          City: {
            type: 'string',
            description: 'City, district, suburb, town, or village. This value cannot exceed 100 characters.',
          },
          State: {
            type: 'string',
            description:
              'State, county, province, or region. When `Country` is set to `UnitedStates` this value must be a valid state name or abbreviation. If the value is `Canada` this value must be a valid Canadian province. For all other countries this field is optional and not validated.',
          },
        },
        required: ['AddressLine1', 'Country', 'PostalCode'],
      },
      UnitNumber: {
        type: 'string',
        description:
          'Unit number. Must be unique within the rental property and cannot exceed 30 characters.',
      },
      Description: {
        type: 'string',
        description: 'Description of the unit. The description cannot exceed 65,535 characters.',
      },
      MarketRent: {
        type: 'number',
        description:
          'Market rent of the unit. This value is separate from the lease rent and is typically used for rental listings.',
      },
      UnitBathrooms: {
        type: 'string',
        description: 'Number of bathrooms in the unit.',
        enum: [
          'NotSet',
          'OneBath',
          'OnePointFiveBath',
          'TwoBath',
          'TwoPointFiveBath',
          'ThreeBath',
          'FourBath',
          'FiveBath',
          'FivePlusBath',
          'ThreePointFiveBath',
          'FourPointFiveBath',
        ],
      },
      UnitBedrooms: {
        type: 'string',
        description: 'Number of bedrooms in the unit.',
        enum: [
          'NotSet',
          'Studio',
          'OneBed',
          'TwoBed',
          'ThreeBed',
          'FourBed',
          'FiveBed',
          'SixBed',
          'SevenBed',
          'EightBed',
          'NineBedPlus',
        ],
      },
      UnitSize: {
        type: 'integer',
        description: 'Size of the unit.',
      },
    },
  },
};

export const handler = async (client: WpmMcpServer, args: Record<string, unknown> | undefined) => {
  const { unitId, ...body } = args as any;
  return asTextContentResult(await client.rentals.units.update(unitId, body));
};

export default { metadata, tool, handler };
